"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SendRequest(google.protobuf.message.Message):
    """Data Structures"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    SELF_EMAIL_FIELD_NUMBER: builtins.int
    DEST_EMAIL_FIELD_NUMBER: builtins.int
    id: builtins.int
    msg: builtins.str
    self_email: builtins.str
    dest_email: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        msg: builtins.str = ...,
        self_email: builtins.str = ...,
        dest_email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dest_email", b"dest_email", "id", b"id", "msg", b"msg", "self_email", b"self_email"]) -> None: ...

global___SendRequest = SendRequest

@typing_extensions.final
class SendResponse(google.protobuf.message.Message):
    """Extensibility"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    DEBUG_MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    debug_message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        debug_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["debug_message", b"debug_message", "success", b"success"]) -> None: ...

global___SendResponse = SendResponse

@typing_extensions.final
class ReceiveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SELF_EMAIL_FIELD_NUMBER: builtins.int
    self_email: builtins.str
    def __init__(
        self,
        *,
        self_email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["self_email", b"self_email"]) -> None: ...

global___ReceiveRequest = ReceiveRequest

@typing_extensions.final
class InboxResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SendRequest]:
        """Returns a list of the original message objects"""
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[global___SendRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["messages", b"messages"]) -> None: ...

global___InboxResponse = InboxResponse
