"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import grpc
import grpc.aio
import messenger_pb2
import typing

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class MessengerServiceStub:
    """The Service Definition"""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Send: grpc.UnaryUnaryMultiCallable[
        messenger_pb2.SendRequest,
        messenger_pb2.SendResponse,
    ]
    """Sends a message destined for a specific IP/Port"""
    ReceiveAll: grpc.UnaryUnaryMultiCallable[
        messenger_pb2.ReceiveRequest,
        messenger_pb2.InboxResponse,
    ]
    """Retrieves all messages waiting for the requester's IP/Port"""

class MessengerServiceAsyncStub:
    """The Service Definition"""

    Send: grpc.aio.UnaryUnaryMultiCallable[
        messenger_pb2.SendRequest,
        messenger_pb2.SendResponse,
    ]
    """Sends a message destined for a specific IP/Port"""
    ReceiveAll: grpc.aio.UnaryUnaryMultiCallable[
        messenger_pb2.ReceiveRequest,
        messenger_pb2.InboxResponse,
    ]
    """Retrieves all messages waiting for the requester's IP/Port"""

class MessengerServiceServicer(metaclass=abc.ABCMeta):
    """The Service Definition"""

    @abc.abstractmethod
    def Send(
        self,
        request: messenger_pb2.SendRequest,
        context: _ServicerContext,
    ) -> typing.Union[messenger_pb2.SendResponse, collections.abc.Awaitable[messenger_pb2.SendResponse]]:
        """Sends a message destined for a specific IP/Port"""
    @abc.abstractmethod
    def ReceiveAll(
        self,
        request: messenger_pb2.ReceiveRequest,
        context: _ServicerContext,
    ) -> typing.Union[messenger_pb2.InboxResponse, collections.abc.Awaitable[messenger_pb2.InboxResponse]]:
        """Retrieves all messages waiting for the requester's IP/Port"""

def add_MessengerServiceServicer_to_server(servicer: MessengerServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
