"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SendRequest(google.protobuf.message.Message):
    """Data Structures"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    SENDPORT_FIELD_NUMBER: builtins.int
    SENDIP_FIELD_NUMBER: builtins.int
    id: builtins.int
    msg: builtins.str
    sendport: builtins.int
    """The destination port"""
    sendip: builtins.str
    """The destination IP"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        msg: builtins.str = ...,
        sendport: builtins.int = ...,
        sendip: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "msg", b"msg", "sendip", b"sendip", "sendport", b"sendport"]) -> None: ...

global___SendRequest = SendRequest

@typing_extensions.final
class SendResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> None: ...

global___SendResponse = SendResponse

@typing_extensions.final
class ReceiveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SELFPORT_FIELD_NUMBER: builtins.int
    SELFIP_FIELD_NUMBER: builtins.int
    selfport: builtins.int
    """Identifying who is asking"""
    selfip: builtins.str
    def __init__(
        self,
        *,
        selfport: builtins.int = ...,
        selfip: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["selfip", b"selfip", "selfport", b"selfport"]) -> None: ...

global___ReceiveRequest = ReceiveRequest

@typing_extensions.final
class InboxResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SendRequest]:
        """Returns a list of the original message objects"""
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[global___SendRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["messages", b"messages"]) -> None: ...

global___InboxResponse = InboxResponse
